nacos:
    enable: true
    client:
        namespace-id: ""
        timeout-ms: 5000
        not-load-cache-at-start: true
        log-dir: /tmp/nacos/log
        cache-dir: /tmp/nacos/cache
        log-level: debug
    server:
        - ip-addr: localhost
          port: 8848
          scheme: http
          context-path: /nacos
    register:
        ip: 127.0.0.1
        port: 14521
        service-name: user-service
        weight: 10
        enable: true
        healthy: true
        ephemeral: true
    config:
        data-id: user-service.yaml
        group: DEFAULT_GROUP
